### PR TITLE
Replace solr search with Google custom search

### PR DESCRIPTION
**Pull request by ZiqiXiong**
This commit replaces Solr/Haystack search with Google custom search, which is easier to maintain and provides more elastic search results (at the cost of less consistent style).

screenshot 2016-11-22 00 43 29
screenshot 2016-11-22 12 16 44

### CODE REVIEW

**Comment by ZiqiXiong** [comment]
@KentShikama  Thoughts?

**Comment by KentShikama** [comment]
@ZiqiXiong at the cost of less consistent style might be an understatement but as long as Solr isn't fixed, I can't compalin

**Comment by ZiqiXiong** [comment]
@KentShikama To use Solr, we not only have to fix it, but also need the bold assumption that everyone developing for TSL in the future knows how to fix it.

**Comment by ZiqiXiong** [comment]
@KentShikama You can also stylize the search result in front-style.css if you have time.

**Comment by KentShikama** [comment]
That is an important point too. I don't oppose this change; I just don't like it lol.

**Comment by ZiqiXiong** [comment]
@KentShikama You wanna merge it then or suggest any improvements?

**Comment by KentShikama** [comment]
Just curious but is it possible to have the previous search bar style back and just scrape the search query term and feed it into Google's search?

**Comment by ZiqiXiong** [comment]
I don't think that's an easy thing to do but I can try to customize the button in Google Custom Search control panel.

**Comment by KentShikama** [comment]
Also remove that `<h2>Search Results for '{{ query }}'</h2>` if you haven't already

**Comment by ZiqiXiong** [comment]
@KentShikama 
screenshot 2016-11-22 12 57 47
screenshot 2016-11-22 12 57 56

**Pull request merged**
